import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:5173';
const date=new Date(Date.now()+3*86400000).toISOString().slice(0,10);
const baseOrder={name:'Test Customer',phone:'0501234567',date,slot:'12:00',fulfilment:'pickup',address:'',notes:'Automated local test',website:'',items:[{id:'sourdough',quantity:2,price:1}],total:1};
let checks=0;function check(actual,expected,label){assert.deepEqual(actual,expected,label);checks++;console.log('PASS '+label)}
async function create(body,key=crypto.randomUUID()){const response=await fetch(base+'/api/orders',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(body)});return {status:response.status,body:await response.json()}}
check((await fetch(base+'/api/admin/orders')).status,401,'anonymous admin read denied');
check((await fetch(base+'/api/admin/orders/missing',{method:'PATCH',headers:{'Content-Type':'application/json'},body:'{}'})).status,401,'anonymous status write denied');
for(const [change,error] of [[{phone:'123'},'phone'],[{name:''},'invalid'],[{date:'2026-02-30'},'date'],[{date:new Date().toISOString().slice(0,10)},'date'],[{items:[]},'cart'],[{items:[{id:'unknown',quantity:1}]},'cart'],[{items:[{id:'cookie',quantity:21}]},'cart'],[{fulfilment:'delivery',address:''},'address'],[{website:'spam'},'invalid']])check((await create({...baseOrder,...change})).body.error,error,'reject '+error+' '+JSON.stringify(change));
const key=crypto.randomUUID();const first=await create(baseOrder,key);check(first.status,201,'pickup saved');check(first.body.total,5600,'server ignores tampered prices');const repeat=await create(baseOrder,key);check(repeat.body.reference,first.body.reference,'retry returns same reference');check((await create({...baseOrder,name:'Changed'},key)).status,409,'key reuse with changed payload rejected');
const delivery=await create({...baseOrder,phone:'0501234568',fulfilment:'delivery',address:'Riyadh Al Malqa Street 12'});check(delivery.body.total,7100,'delivery fee SAR 15');
const raceKey=crypto.randomUUID();const races=await Promise.all([create({...baseOrder,phone:'0501234569'},raceKey),create({...baseOrder,phone:'0501234569'},raceKey)]);check(races[0].body.reference,races[1].body.reference,'concurrent duplicates return one order');
const bad=await fetch(base+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'devtest@gmail.com',password:'wrong'})});check(bad.status,401,'incorrect password denied');
const login=await fetch(base+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'devtest@gmail.com',password:'devtest'})});check(login.status,200,'email/password login');const cookie=login.headers.get('set-cookie').split(';')[0];check(login.headers.get('set-cookie').includes('HttpOnly'),true,'session HttpOnly');
const headers={Cookie:cookie,'Content-Type':'application/json'};const list=await (await fetch(base+'/api/admin/orders',{headers})).json();check(Array.isArray(list.orders),true,'authenticated listing');const order=list.orders.find(o=>o.reference===first.body.reference);assert(order);check(order.items[0].quantity,2,'line items persisted');
check((await (await fetch(base+`/api/admin/orders?date=${date}&fulfilment=delivery&status=new`,{headers})).json()).orders.every(o=>o.fulfilment==='delivery'&&o.date===date&&o.status==='new'),true,'combined filters');
async function transition(id,expectedStatus,status){return fetch(base+`/api/admin/orders/${id}`,{method:'PATCH',headers,body:JSON.stringify({expectedStatus,status})})}
check((await transition(order.id,'new','completed')).status,409,'invalid transition rejected');for(const [from,to] of [['new','confirmed'],['confirmed','preparing'],['preparing','ready'],['ready','completed']])check((await transition(order.id,from,to)).status,200,from+' to '+to);
check((await transition(order.id,'ready','cancelled')).status,409,'stale transition rejected');const deliveryOrder=list.orders.find(o=>o.reference===delivery.body.reference);for(const [from,to] of [['new','confirmed'],['confirmed','preparing'],['preparing','out_for_delivery'],['out_for_delivery','completed']])check((await transition(deliveryOrder.id,from,to)).status,200,'delivery '+from+' to '+to);
const raceOrder=list.orders.find(o=>o.reference===races[0].body.reference);check((await transition(raceOrder.id,'new','cancelled')).status,200,'cancellation');
check((await fetch(base+'/api/admin/orders',{headers:{Cookie:cookie+'x'}})).status,401,'forged session rejected');
check((await fetch(base+'/api/admin/logout',{method:'POST',headers})).headers.get('set-cookie').includes('Max-Age=0'),true,'logout clears cookie');console.log(`${checks} API checks passed`);
